### ISSUE TITLE
Blocked by Lulu

### ISSUE THREAD

**Issue by jenbennings** [ianstormtaylor/hpmor#1]
> Dear Account Holder:
> 
> It has come to our attention that your Content may be in violation of the Lulu Membership Agreement, which states that your Content cannot contain material that is intellectual property of another, invasive of privacy rights, defamatory or otherwise questionable and/or determined by us in our sole discretion to violate our Membership Agreement.  As a result, we must remove your content from availability.
> 
> Your order #XXXXXXXX has been refunded.
> 
> For more information on the terms and conditions of publishing through Lulu.com please review our Membership Agreement at http://www.lulu.com/about/legal.  
> 
> You may submit the attached DMCA Counter-notification, or a Court Order clearly stating you have the authority to publish said Content, and we may re-evaluate our decision.
> 
> Please let us know if we can be of any further assistance.
> 
> Regards,
> 
> Questionable Content Team
> Lulu.com

**Comment by greysonp** [comment]
My order just got canceled as well :(

> Dear Account Holder:
> 
> It has come to our attention that your Content, titled "Harry Potter and the Methods of Rationality,” may be in violation of the Lulu Membership Agreement, which states that your Content cannot contain material that is intellectual property of another, invasive of privacy rights, defamatory or otherwise questionable and/or determined by us in our sole discretion to violate our Membership Agreement.  As a result, we must remove your content from availability, cancel order XXXXXXXX, and terminate your Lulu account. You will be refunded for your recent order.
> 
> For more information on the terms and conditions of publishing through Lulu.com please review our Membership Agreement at http://www.lulu.com/about/legal.  
> 
> You may submit the attached DMCA Counter-notification, or a Court Order clearly stating you have the authority to publish said Content, and we may re-evaluate our decision.
> 
> Please let us know if we can be of any further assistance.
> 
> 
> Regards,
> 
> Questionable Content Team
> Lulu.com

**Comment by cpollack** [comment]
Same issue for me. Lulu blocked me. I suspect they have a DMCA bot which blocks anything containing "Harry Potter". I am going to reply and submit the counter DMCA form to see if they will reinstate it.

**Comment by lborthwein** [comment]
Same just happened to me last week @cpollack. I replied to their counter DMCA and was informed that they were not changing their mind and my account was to remain terminated. Anyone know of any alternative printing options?

**Comment by cpollack** [comment]
Indeed. Here is what I got back:

> Dear Account Holder,
> 
> We have reviewed your counter DMCA notice and determined that the Content in question will remain unavailable and Lulu account terminated.

I am going to try to find some alternatives. Will post an update here if I find anything.

**Comment by cpollack** [comment]
Update:
I found a website and was successfully able to print the first book (and received it). It only takes a few minutes to create a book. Just make sure to NOT make it available on the bookstore. I would also advise not including the words "Harry Potter" in the title/description, so as to not trigger any copyright bots, though I do not know of they exist. Prices are a tiny bit higher than Lulu, at maybe $10 at the most expensive.

I went ahead and ordered 2-6. Hopefully they go through without a hitch!
http://www.thebookpatch.com/

**Comment by Kinille** [comment]
I also had this problem.
I had a lot of trouble finding a different book store that would print small volumes of books like lulu. After experimenting, I found that blurb actually charges less than lulu. You can get the whole collection for ≈ $35 (with US shipping) with each book costing between $4 and $7. The only problem is that blurb's PDF upload is a pain to manage. Because I already did the work of reformatting and didn't want anyone else to have to suffer what I just did, I uploaded a separate branch for this repo.

You can find all the files you would need for a blurb upload here.
[https://github.com/GreenMuon/hpmor](https://github.com/GreenMuon/hpmor)

**Comment by traverseda** [comment]
Order went through alright for me. I didn't include real information in the book's metadata page, and ordered a "proof copy"

**Comment by jrincayc** [comment]
For the record, I tried printing HPMOR with Lulu, and only made it available to me, and the order was rejected, and my Lulu account was closed.  This meant that I also lost the money from my book I had on Lulu that I was owed because they only send it when it reaches a minimum level, and I had to put my book up again (requiring a second proof copy).  Also, the terms of service allow them to not refund you if they believe that you are in violation of their content rules, so it is possible you might loose money doing this.

**Comment by ianstormtaylor** [comment]
Really sorry about any people whose account was terminated. I'm not sure when Lulu does and doesn't detect and terminate, but thank you to @GreenMuon and @jrincayc for the pull request that changes over the instructions to use Blurb instead of Lulu.

**Comment by jrincayc** [comment]
@ianstormtaylor Thank you for updating the page and the apology.

**Comment by floofydoug** [comment]
Ah, wish i'd seen this before making my order. Also got blocked, however they said they refunded me... so I didn't lose anything. 

<img width="985" alt="screen shot 2017-10-30 at 1 02 09 am" src="https://user-images.githubusercontent.com/1750326/32155507-1457da28-bd0e-11e7-9409-0c88563ebe5c.png">
